# https://hub.docker.com/_/microsoft-dotnet
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src

# copy csproj and restore as distinct layers
# COPY *.sln .
COPY snsrpi-device/*.csproj .
RUN dotnet restore
RUN dotnet dev-certs https --clean
RUN dotnet dev-certs https -t

# copy everything else and build app
# COPY snsrpi-device/ .
WORKDIR /src
CMD ["dotnet", "watch", "run"]